### ISSUE TITLE
Proposal to add new ModelMesh committers

### ISSUE THREAD

**Issue by ckadner** [kserve/community#6]
We recently codified the process of how outstanding KServe contributors can be promoted to [become committers](https://github.com/kserve/community/blob/main/CONTRIBUTING.md#becoming-a-committer).

This issue starts the process of a first selection of candidates. The output of the `list-contributors.py` script is used as a reference point to help with selecting candidates.
1. Top PR **authors**
2. Top PR **reviewers**
3. Top contributors (PRs **authored and/or reviewed**)

The contribution activity spans the previous 6 months. Current committers and bot accounts are excluded.

Actual candidates to be promoted will be nominated by current committers and (in this first round of promotions) can be voted on by all contributors. 

### 1. Top PR authors:

```shell
$ ./scripts/python/list-contributors.py --repo kserve/modelmesh-serving -n 3 -r author

Contributors to 'kserve/modelmesh-serving' (PR authors) by number of PRs (>3) since 2023-03-22:

 17  rafvasq            [422, 421, 417, 416, 413, 412, 406, 405, 403, 391, 390, 379, ... ]
  7  ckadner            [429, 415, 414, 404, 371, 368, 354]

```

### 2. Top PR reviewers:

```shell
$ ./scripts/python/list-contributors.py --repo kserve/modelmesh-serving  -n 3 -r reviewer commenter

Contributors to 'kserve/modelmesh-serving' (PR commenters, reviewers) by number of PRs (>3) since 2023-03-22:

 25  ckadner            [428, 425, 422, 421, 417, 416, 413, 412, 406, 405, 403, 400, ... ]
  9  rafvasq            [429, 428, 415, 414, 404, 398, 395, 394, 375]

```

### 3. Top contributors (PRs authored and/or reviewed):

```shell
$ ./scripts/python/list-contributors.py --repo kserve/modelmesh-serving -n 3

Contributors to 'kserve/modelmesh-serving' (PR authors, commenters, reviewers) by number of PRs (>3) since 2023-03-22:

 32  ckadner            [429, 428, 425, 422, 421, 417, 416, 415, 414, 413, 412, 406, ... ]
 26  rafvasq            [429, 428, 422, 421, 417, 416, 415, 414, 413, 412, 406, 405, ... ]
  3  Jooho              [400, 397, 363]

```

@njhill

**Comment by ckadner** [comment]
FYI @rafvasq

**Comment by ckadner** [comment]
This could look like I am shamelessly self-promoting here, but, Rafael and Jooho are here too. So it's totally legit!

😎

**Comment by njhill** [comment]
I approve!

**Comment by ckadner** [comment]
> I approve!

Thanks @njhill -- I will go ahead and update the OWNER files in all the ModelMesh repos

**Comment by ckadner** [comment]
Thanks @njhill
